//+------------------------------------------------------------------+
//| CheckCoreSignal.mq5 — compile/smoke gate for                     |
//| Core/CoreSignal.mqh (UNIT 3 of the S2 live-Core build).          |
//|                                                                  |
//| NO trading functions, NO files.  Four blocks:                    |
//|   1. structural smoke: opex calendar (v5_sleeves 3rd-Friday      |
//|      weeks, 375 days), policy step tables, CsDaysFromCivil;      |
//|   2. PYTHON-GOLDEN block: a deterministic synthetic 240-day /    |
//|      1440-bar run (64-bit LCG price walk, IEEE-exact in both     |
//|      languages) through CCoreSignal, compared at 50 sampled bars |
//|      per leg against values generated from the NORMATIVE         |
//|      reference (core_signal_reference.gen_*, fma kernels) by     |
//|      gen_coresignal_check_golden.py.  Criterion = the owner-     |
//|      ratified max|d| <= 1e-12 AND 0 sign flips (the mirror       |
//|      measured the fma emulation bit-equal, so bit-zero is        |
//|      expected — the bit count is reported);                      |
//|   3. state round-trip: GetState -> fresh SetState mid-run, blob  |
//|      string equality, then both objects stepped to the end with  |
//|      every target bit-compared (+ defer-hold invariants);        |
//|   4. CCoreTrigger smoke: band fire with min-gap suppression      |
//|      (breach on a skipped day does NOT latch), harvest fire      |
//|      without gap, hold-at-legcap held-row telemetry, state       |
//|      round-trip, non-ascending-day guard.                        |
//|                                                                  |
//| The terminal Print output must end with                          |
//| "CheckCoreSignal: ALL PASS".                                     |
//+------------------------------------------------------------------+
#property copyright "FMA3"
#property version   "1.00"

#include <Core/CoreSignal.mqh>

int g_fail = 0;

void Expect(const bool ok, const string what)
  {
   if(!ok)
     {
      g_fail++;
      Print("CheckCoreSignal FAIL: ", what);
     }
  }

//==================================================================//
// synthetic schedule + LCG (MUST match gen_coresignal_check_golden //
// verbatim: 240 days from eday 19723, hours {1,10,19,21,22,23}     //
// minute 30; per-instrument 64-bit LCG price walk)                 //
//==================================================================//
#define CSG_NDAYS 240
#define CSG_E0    19723          // 2024-01-01 (Monday)
#define CSG_NBPD  6
#define CSG_NBARS 1440           // CSG_NDAYS * CSG_NBPD
#define CSG_SPLIT 700            // state round-trip bar index

int    CSG_HOURS[CSG_NBPD] = {1, 10, 19, 21, 22, 23};
double CSG_BASE[CS_NINST]  = {2000.0, 150.0, 3000.0, 0.85,
                              18000.0, 0.65, 0.60, 60000.0};

// ---- python-golden block (GENERATED by gen_coresignal_check_golden.py — do not edit) ----
#define CSG_NSAMP 50
int CSG_SAMPLE_POS[CSG_NSAMP] =
  {557, 575, 593, 611, 629, 647, 665, 683, 701, 719,
   737, 755, 773, 791, 809, 827, 845, 863, 881, 899,
   917, 935, 953, 971, 989, 1007, 1025, 1043, 1061, 1079,
   1097, 1115, 1133, 1151, 1169, 1187, 1205, 1223, 1241, 1259,
   1277, 1295, 1313, 1331, 1349, 1367, 1385, 1403, 1421, 1439};
// reference targets (fma kernels) at the sampled bars, %.17g
double CSG_EXPECT[9][CSG_NSAMP] =
  {
   {5.8458963794163683, 5.8266273016434553, 5.5366126623686736, 5.3561918653278422, 5.4598916722479123,
    5.4247326239990983, 5.8315987089774701, 6, 6, 6,
    6, 5.8330102577413641, 5.8489375360182843, 5.4747774262074742, 5.4198778303311723,
    5.4882867090789347, 8.0673233840282155, 8.7279937962629397, 8.6065175360187034, 8.8333333333333339,
    8.8333333333333339, 8.8333333333333339, 8.238033158336119, 8.1338989241357051, 7.6361757187803061,
    7.6709473202374481, 7.5959515622891915, 7.4761634400199064, 7.778098793198966, 7.1303910234146102,
    7.0061185595944995, 6.9869933202590211, 7.1948699260277582, 6.9018722804279111, 7.4422204079995131,
    7.5828637302299864, 7.1516603522216649, 7.1562878196455664, 6.853916096842859, 7.1063290894616138,
    7.1242070712871683, 7.5767013198126429, 7.0062385053922318, 7.3609274673990015, 6.6669718758006882,
    6.8371933651242038, 6.8888342155691662, 6.9581430399219286, 6.88383694650559, 7.2016924073121107},
   {0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 6.0568470022541669, 0,
    6.5319461202545659, 6.5967643438698236, 6.8337168036209794, 6.6981262575790499, 6.510669915203966,
    7.2759252314000218, 3.973265914475455, 7.8095060753067465, 7.4864239060588833, 7.9651051690408545,
    3.4669531898210999, 2.9216840792378971, 5.4604758444055967, 2.5588931727230486, 2.5877927358334816,
    5.3109547103191694, 4.8624069659630829, 4.7787936765893582, 2.5862015147018846, 5.0624367460700013,
    4.7902969061866187, 4.6992563137828229, 4.6299880776836551, 6.3907304809258187, 5.9568505482419134,
    6.2463832633121674, 6.3124818710004718, 6.7765404173167108, 5.8569824293446997, 5.2654216764603738},
   {0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 1.2, 1.2, 1.2, 1.2,
    1.2, 1.2, 1.2, 0, 0,
    0, 0, 1.2, 1.2, 1.2},
   {1.9256949570187329, 3.5080785016003238, 1.7147028497819694, 3.5375601154712104, 3.0089989918900542,
    6.9492519072413721, 0.09976145690064718, 0.49458910947856849, 1.0251546069554776, -0.48181835025510422,
    -3.9926966923485732, -7.8935014782678143, -2.0906891908538956, -2.7171649624289742, -4.9482265170124107,
    -7.1918158714771856, -5.4039968405395573, -3.6571221686062274, -4.9172371052870707, -4.3244430888432834,
    -3.3681743400356714, -3.0953654175600356, -3.421105202786817, 0.44649904069533908, 0.015643619241844556,
    0.56881478493096926, 2.8384148263016891, 1.183632419139814, -2.9475401192387314, -1.4465305258396488,
    -3.8887839767204184, -5.8785211445696275, -2.0361792104246561, -3.7475054271314545, -3.3634836932278458,
    -2.1430837589275509, -6.0090128441331379, -7.2212157774691841, -6.5243922511156782, -9.3747052054850233,
    -9.1994996910320133, -10.065608763931587, -8.0390257984494013, -8.13819188672956, -2.6257157221361602,
    -5.6756074998801589, -1.7921973701368219, -0.71773913862654981, -3.4018380191360951, -5.1349266720451574},
   {0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 2.25, 2.25, 2.25, 2.25,
    2.25, 2.25, 2.25, 2.25, 2.25,
    2.25, 2.25, 2.25, 2.25, 2.25},
   {0, 0, 0, 0, 0,
    5.2450819991847926, 0, 0, 0, 0,
    0, 0, 0, 0, 5.8883745988964531,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 6, 0, 0, 0,
    0, 0, 0, 0, 0,
    5.3109547103191694, 0, 0, 0, 0,
    0, 0, 0, 0, 5.9568505482419134,
    6, 0, 0, 0, 0},
   {-0, -0, -0, -0, -0,
    -5.2933976681507158, -0, -0, -0, -0,
    -0, -0, -0, -0, -5.4699429882966308,
    0, -0, -0, -0, -0,
    -0, -0, -0, -0, -0,
    -0, -4.5127791214475712, -0, -0, -0,
    -0, -0, -0, -0, -0,
    -5.5913184178114061, 0, -0, -0, -0,
    -0, -0, -0, -0, -4.5688162338297564,
    -4.8150552001884517, 0, -0, -0, -0},
   {-0, -0, -0, -0, -0,
    -3.9616699833322784, -0, -0, -0, -0,
    -0, -0, -0, -0, -5.6806501926993418,
    0, -0, -0, -0, -0,
    -0, -0, -0, -0, -0,
    -0, -4.2964113160391459, -0, -0, -0,
    -0, -0, -0, -0, -0,
    -5.4662513097854584, 0, -0, -0, -0,
    -0, -0, -0, -0, -6,
    -6, 0, -0, -0, -0},
   {0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 0, 0, 0, 0,
    0, 1.2, 1.2, 1.2, 1.2,
    1.2, 1.2, 1.2, 1.2, 1.2,
    1.2, 1.2, 1.2, 1.2, 1.2}
  };
// ---- end python-golden block ----

double g_mine[9][CSG_NBARS];     // primary-object targets, every bar

double CsgSign(const double x)
  {
   if(x > 0.0) return 1.0;
   if(x < 0.0) return -1.0;
   return 0.0;
  }

//+------------------------------------------------------------------+
void SmokeTables(void)
  {
   //--- CsDaysFromCivil
   Expect(CsDaysFromCivil(1970, 1, 1) == 0,      "days_from_civil 1970-01-01");
   Expect(CsDaysFromCivil(2024, 1, 1) == 19723,  "days_from_civil 2024-01-01");
   Expect(CsDaysFromCivil(2019, 12, 1) == 18231, "days_from_civil 2019-12-01");
   Expect(CsDaysFromCivil(2026, 2, 1) == 20485,  "days_from_civil 2026-02-01");

   //--- opex calendar (375 days, 2019-12 .. 2026-02)
   CCsOpexCal cal;
   cal.Init();
   Expect(cal.Count() == 375,   "opex count 375");
   Expect(cal.First() == 18246, "opex first 2019-12-16");
   Expect(cal.Last() == 20504,  "opex last 2026-02-20");
   Expect(cal.In(19947),  "opex 2024-08-12 in");     // Mon of Aug-2024 week
   Expect(cal.In(19951),  "opex 2024-08-16 in");     // 3rd Friday
   Expect(!cal.In(19954), "opex 2024-08-19 out");
   Expect(cal.In(18337),  "opex 2020-03-16 in");
   Expect(cal.In(20500),  "opex 2026-02-16 in");
   Expect(!cal.In(18245), "opex 2019-12-15 out");

   //--- policy step tables
   CCsPolicy pol;
   pol.Init();
   Expect(pol.RateUsd(18200) == 1.625, "usd before-first -> rates[0]");
   Expect(pol.RateUsd(18201) == 1.625, "usd 2019-11-01");
   Expect(pol.RateUsd(18336) == 0.125, "usd 2020-03-15");
   Expect(pol.RateUsd(18400) == 0.125, "usd mid-2020");
   Expect(pol.RateUsd(19999) == 4.875, "usd 2024-10");
   Expect(pol.RateUsd(20433) == 3.625, "usd 2025-12-11");
   Expect(pol.RateJpy(19800) == -0.10, "jpy pre-hike");
   Expect(pol.RateJpy(19801) == 0.10,  "jpy 2024-03-19");
   Expect(pol.RateJpy(19935) == 0.25,  "jpy 2024-07-31");
   Expect(pol.RateJpy(20112) == 0.50,  "jpy 2025-01-24");
  }

//+------------------------------------------------------------------+
void SyntheticGoldenRun(void)
  {
   ulong  s[CS_NINST];
   double m[CS_NINST];
   for(int i = 0; i < CS_NINST; i++)
     {
      s[i] = (ulong)0x9E3779B97F4A7C15 * (ulong)(i + 1);
      m[i] = CSG_BASE[i];
     }

   CCoreSignal sig;
   sig.Configure();
   CCoreSignal sig2;                 // restored twin (from CSG_SPLIT on)
   sig2.Configure();
   bool restored = false;
   long tail_diffs = 0;

   int k = 0;
   for(int day = 0; day < CSG_NDAYS; day++)
     {
      for(int hh = 0; hh < CSG_NBPD; hh++)
        {
         long ts = ((long)(CSG_E0 + day)) * 86400
                   + (long)CSG_HOURS[hh] * 3600 + 1800;
         for(int i = 0; i < CS_NINST; i++)
           {
            s[i] = s[i] * 6364136223846793005 + 1442695040888963407;
            double u = (double)((s[i] >> 40) & 0xFFFFFF) / 16777216.0;
            m[i] = m[i] * (1.0 + ((u - 0.5) * 0.02 + 0.0004));
            double spr = m[i] * 0.0003;
            double bid = m[i] - spr * 0.5;
            double ask = m[i] + spr * 0.5;
            Expect(sig.StepBar(i, ts, bid, ask),
                   "StepBar " + sig.LastError());
            if(restored)
               Expect(sig2.StepBar(i, ts, bid, ask),
                      "twin StepBar " + sig2.LastError());
           }
         for(int leg = 0; leg < CS_NLEGS; leg++)
           {
            g_mine[leg][k] = sig.Tgt(leg);
            if(restored && sig2.Tgt(leg) != sig.Tgt(leg))
               tail_diffs++;
           }
         //--- state round-trip at the split bar --------------------
         if(k == CSG_SPLIT)
           {
            string s1 = sig.GetState();
            Expect(sig2.SetState(s1), "SetState: " + sig2.LastError());
            string s2 = sig2.GetState();
            Expect(s1 == s2, "state round-trip blob equality");
            PrintFormat("CheckCoreSignal state: blob %d chars, round-trip %s",
                        StringLen(s1), (s1 == s2) ? "EXACT" : "DIFFERS");
            restored = true;
           }
         k++;
        }
     }
   Expect(k == CSG_NBARS, "bar count");
   Expect(tail_diffs == 0, StringFormat("restored-twin tail: %I64d target "
                                        "diffs (must be 0)", tail_diffs));
   PrintFormat("CheckCoreSignal split: restored twin re-stepped bars %d..%d, "
               "target diffs = %I64d", CSG_SPLIT + 1, CSG_NBARS - 1, tail_diffs);

   //--- python-golden comparison at the sampled bars ----------------
   bool all_ok = true;
   for(int leg = 0; leg < CS_NLEGS; leg++)
     {
      int    nbit = 0, flips = 0, ngt = 0;
      double maxd = 0.0;
      for(int q = 0; q < CSG_NSAMP; q++)
        {
         double mine = g_mine[leg][CSG_SAMPLE_POS[q]];
         double gold = CSG_EXPECT[leg][q];
         if(mine == gold)
            nbit++;
         double dd = MathAbs(mine - gold);
         if(dd > maxd) maxd = dd;
         if(dd > 1e-12) ngt++;
         if(CsgSign(mine) != CsgSign(gold)) flips++;
        }
      bool ok = (maxd <= 1e-12 && flips == 0);
      all_ok = all_ok && ok;
      PrintFormat("CheckCoreSignal golden leg %d: bit %d/%d max|d|=%.3e "
                  ">1e-12: %d flips=%d %s",
                  leg, nbit, CSG_NSAMP, maxd, ngt, flips, ok ? "OK" : "FAIL");
      Expect(ok, StringFormat("golden leg %d (max|d|=%.3e flips=%d)",
                              leg, maxd, flips));
     }

   //--- defer-hold invariant on the last synthetic day --------------
   // bar layout per day: h in {1,10,19,21,22,23} -> the 21:30 and 22:30
   // outputs of the deferred legs 0..4 must equal the 19:30 output
   int base = (CSG_NDAYS - 1) * CSG_NBPD;
   for(int leg2 = 0; leg2 <= 4; leg2++)
     {
      Expect(g_mine[leg2][base + 3] == g_mine[leg2][base + 2],
             StringFormat("defer hold leg %d @21h", leg2));
      Expect(g_mine[leg2][base + 4] == g_mine[leg2][base + 2],
             StringFormat("defer hold leg %d @22h", leg2));
     }

   //--- ascending-stamp guard ----------------------------------------
   Expect(!sig.StepBar(0, 1000, 1.0, 1.0), "stale stamp must be refused");
  }

//+------------------------------------------------------------------+
void SmokeTrigger(void)
  {
   int legSlot[9] = {0, 1, 2, 3, 4, 5, 5, 5, 6};
   double up = 0.25;
   double down = (1.0 / 7.0) / 1.75;
   CCoreTrigger trig;
   Expect(trig.Configure(7, 9, legSlot, up, down, 2.5, 5),
          "trigger Configure: " + trig.LastError());

   long D0 = 20000;
   bool fired = false;

   //--- (a) band fire with min-gap suppression -----------------------
   // slot 0 breaches shares (2300/8300 = 0.277 > 0.25) from day D0+2 on
   // but stays below the harvest thr (2300 < 2.5*7000/7 = 2500); the
   // breach must NOT latch on days D0+2..D0+4 (gap < 5) and must fire
   // on the D0+5 row (gap = 5), act D0+6.
   Expect(trig.BeginSegment(7000.0, D0), "BeginSegment a");
   for(long dd = D0 + 1; dd <= D0 + 6; dd++)
     {
      long ts = dd * 86400 + 3600;
      Expect(trig.CheckDay(ts, fired), "CheckDay a: " + trig.LastError());
      if(dd < D0 + 6)
         Expect(!fired, StringFormat("premature fire day +%d", (int)(dd - D0)));
      else
        {
         Expect(fired, "band must fire on the +5 row");
         if(fired)
           {
            Expect(trig.Kind() == "band",        "kind band");
            Expect(trig.DecidedDay() == D0 + 5,  "decided day +5");
            Expect(trig.ActDay() == D0 + 6,      "act day +6");
            Expect(trig.MaxSlot() == 0,          "max slot 0");
            Expect(trig.MaxShare() > 0.25,       "max share > up");
           }
        }
      if(fired)
         break;
      for(int l = 0; l < 9; l++)
        {
         double eq;
         if(l == 0)
            eq = (dd >= D0 + 2) ? 2300.0 : 1000.0;
         else if(l >= 5 && l <= 7)
            eq = 1000.0 / 3.0;
         else
            eq = 1000.0;
         Expect(trig.OnLegBar(l, ts, eq), "OnLegBar a");
        }
     }

   //--- (b) harvest fires with NO min-gap -----------------------------
   Expect(trig.BeginSegment(7000.0, D0), "BeginSegment b");
   for(int l2 = 0; l2 < 9; l2++)
     {
      double eq = (l2 == 2) ? 2600.0
                  : ((l2 >= 5 && l2 <= 7) ? 1000.0 / 3.0 : 1000.0);
      Expect(trig.OnLegBar(l2, (D0 + 1) * 86400 + 3600, eq), "OnLegBar b");
     }
   Expect(trig.CheckDay((D0 + 2) * 86400 + 3600, fired), "CheckDay b");
   Expect(fired, "harvest must fire without gap");
   if(fired)
     {
      Expect(trig.Kind() == "harvest",       "kind harvest");
      Expect(trig.DecidedDay() == D0 + 1,    "decided day +1");
      Expect(trig.ActDay() == D0 + 2,        "act day +2");
     }

   //--- (c) hold-at-legcap held-row telemetry -------------------------
   long held0 = trig.HeldRows();
   long rows0 = trig.RowsScanned();
   Expect(trig.BeginSegment(7000.0, D0), "BeginSegment c");
   for(int l3 = 0; l3 < 9; l3++)
     {
      if(l3 >= 5 && l3 <= 7)
         continue;                        // the S6 slot never prints
      Expect(trig.OnLegBar(l3, (D0 + 1) * 86400 + 3600, 1000.0), "OnLegBar c");
     }
   Expect(trig.CheckDay((D0 + 2) * 86400 + 3600, fired), "CheckDay c");
   Expect(!fired, "legcap-held equal shares must not fire");
   Expect(trig.RowsScanned() == rows0 + 1, "rows_scanned +1");
   Expect(trig.HeldRows() == held0 + 1,    "held_rows +1 (S6 held)");

   //--- (d) state round-trip ------------------------------------------
   string t1 = trig.GetState();
   CCoreTrigger trig2;
   Expect(trig2.Configure(7, 9, legSlot, up, down, 2.5, 5), "Configure d");
   Expect(trig2.SetState(t1), "trigger SetState: " + trig2.LastError());
   Expect(trig2.GetState() == t1, "trigger state round-trip equality");

   //--- (e) non-ascending day guard -----------------------------------
   Expect(!trig.CheckDay((D0 - 5) * 86400, fired), "stale day must be refused");
  }

//+------------------------------------------------------------------+
void OnStart()
  {
   Print("CheckCoreSignal: structural smoke + synthetic python-golden run ...");
   SmokeTables();
   SyntheticGoldenRun();
   SmokeTrigger();
   if(g_fail == 0)
      Print("CheckCoreSignal: ALL PASS");
   else
      PrintFormat("CheckCoreSignal: %d FAILURES", g_fail);
  }
//+------------------------------------------------------------------+
